# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from selenium.webdriver.support.ui import Select

class TestCc5764():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_cc5764(self):
    self.driver.get("http://localhost:8080/altacamino")
    scroll0 = "window.scrollTo(0,0)"
    scroll400 = "window.scrollTo(0,400)"
    scroll800 = "window.scrollTo(0,800)"
    self.driver.maximize_window()
    self.driver.execute_script(scroll400)
    estado = self.driver.find_element(By.ID, "estado")
    estado.send_keys("Oaxaca")       
    self.driver.find_element(By.ID, "datosNivelMunicipal").click()
    time.sleep(5)    
    self.driver.find_element(By.ID, "municipio").send_keys("Mariscala de Juárez")   
    self.driver.find_element(By.ID, "datosNivelMunicipal").click() 
    self.driver.execute_script(scroll400)
    time.sleep(5)
    self.driver.find_element(By.CLASS_NAME, "e-multi-select-wrapper").click()         
    self.driver.find_element(By.XPATH, '//*[text()="San Pedro Atoyac"]').click()
    self.driver.find_element(By.ID, "datosNivelMunicipal").click()
    self.driver.execute_script(scroll400)
    time.sleep(2)
    self.driver.find_element(By.CLASS_NAME, "e-multi-select-wrapper").click()         
    self.driver.find_element(By.XPATH, '//*[text()="San Miguel Carrizal"]').click()
    self.driver.find_element(By.ID, "datosNivelMunicipal").click()
    self.driver.execute_script(scroll400)
    time.sleep(2)
    region = self.driver.find_element(By.ID, "region")
    region.send_keys("Prueba Robot región")
    time.sleep(2)
    ubicacion = self.driver.find_element(By.ID, "ubicacion")
    ubicacion.send_keys("Prueba Robot ubicación")
    time.sleep(3)
    self.driver.execute_script(scroll800)
    time.sleep(5)
    self.driver.execute_script(scroll400)
    self.driver.find_element_by_link_text("Datos del Camino").click()
    time.sleep(2)
    estrategia = self.driver.find_element(By.ID, "trenMaya")
    estrategia.click()
    time.sleep(2)
    agencia = self.driver.find_element(By.ID,"agencia")
    agencia.click()
    time.sleep(2)
    nombre_camino = self.driver.find_element(By.ID, "nombreCamino")
    nombre_camino.send_keys("Prueba Robot Nombre Camino")
    time.sleep(2)
    longitud = self.driver.find_element(By.ID, "longitud")
    longitud.send_keys("1260.50")
    time.sleep(2)        
    longitud_pavimentar = self.driver.find_element(By.ID, "longitudPavimentar")
    longitud_pavimentar.send_keys("1100.10")
    time.sleep(2)        
    ancho_camino = self.driver.find_element(By.ID, "anchoCamino")
    ancho_camino.send_keys("5")
    time.sleep(2)
    ubicacion_camino = self.driver.find_element(By.ID, "ubicacionCamino")
    ubicacion_camino.send_keys("Prueba Robot ubicación del camino xxxxxx")        
    time.sleep(2)
    caracteristicas_camino = self.driver.find_element(By.ID, "caracteristicasCamino")
    caracteristicas_camino.send_keys("Prueba Robot caracteristicas del camino xxxxxx")        
    time.sleep(2)
    beneficios_camino = self.driver.find_element(By.ID, "beneficiosCamino")
    beneficios_camino.send_keys("Prueba Robot Beneficios del camino xxxxxx")        
    time.sleep(2) 
    self.driver.execute_script(scroll0)   
    time.sleep(2) 
    self.driver.find_element(By.ID, "tabDatosBeneficiario").click()
    time.sleep(2)
    self.driver.execute_script(scroll400)   
    nombre = self.driver.find_element(By.ID, "nombre")
    nombre.send_keys("Prueba robot Nombre")
    time.sleep(2)
    nombre = self.driver.find_element(By.ID, "papellido")
    nombre.send_keys("Prueba robot Primer apellido")
    time.sleep(2)
    nombre = self.driver.find_element(By.ID, "sapellido")
    nombre.send_keys("Prueba robot Segundo apellido")
    time.sleep(2)
    rfc = self.driver.find_element(By.ID, "rfc")
    rfc.send_keys("rcfpruebarobot")
    time.sleep(2)
    cuenta = self.driver.find_element(By.ID, "cuenta")
    cuenta.send_keys("4763843824238")    
    time.sleep(2)
    numexterior = self.driver.find_element(By.ID, "numexterior")
    numexterior.send_keys("1031")
    time.sleep(2)
    calle = self.driver.find_element(By.ID, "calle")
    calle.send_keys("prueba robot calle xxx")
    time.sleep(2)
    colonia = self.driver.find_element(By.ID, "colonia")
    colonia.send_keys("prueba robot colonia xxx")
    time.sleep(2)
    codpostal = self.driver.find_element(By.ID, "codpostal")
    codpostal.send_keys("prueba robot codpostal xxx")
    time.sleep(2)
    tipocalle = self.driver.find_element(By.ID, "tipocalle")
    tipocalle.send_keys("prueba robot tipocalle xxx")
    time.sleep(2)
    select_tipo_calle = Select(self.driver.find_element_by_id('tipocalle'))
    select_tipo_calle.select_by_visible_text('Privada')
    time.sleep(3)
    self.driver.execute_script(scroll400)
    time.sleep(3)
    


    