# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from selenium.webdriver.support.ui import Select
from selenium.webdriver.chrome.options import Options

class TestCc5764():
  def setup_method(self, method):
    options = Options()
    options.binary_location = '/usr/bin/google-chrome-beta'      
    self.driver = webdriver.Chrome(options = options)    
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_cc5764(self):
    scroll400 = "window.scrollTo(0,400)"
    self.driver.get("https://cmqa.sct.gob.mx/")
    self.driver.maximize_window()
    time.sleep(5) 
    self.driver.find_element(By.ID, "sbtlogin").click()            
    time.sleep(5) 
    user = self.driver.find_element(By.ID, "user")
    user.send_keys("jose.cruz")           
    pwd = self.driver.find_element(By.ID, "contrasenia")
    pwd.send_keys("internet")  
    time.sleep(5) 
    self.driver.find_element(By.ID, "sbtlogin").click()         
    time.sleep(5) 
    self.driver.execute_script(scroll400)
    self.driver.find_element(By.ID, "buscarObras").click()         
    time.sleep(5) 
    select_edo = Select(self.driver.find_element_by_id("estado"))
    select_edo.select_by_index(5)
    time.sleep(3) 
    select_edo = Select(self.driver.find_element_by_id("municipio"))
    select_edo.select_by_index(5)
    time.sleep(3) 
    select_edo = Select(self.driver.find_element_by_id("localidad"))
    select_edo.select_by_index(2)
    time.sleep(2) 
    self.driver.find_element(By.ID, "b2").click()       
    time.sleep(2)
    self.driver.find_element(By.ID, "buscarObras").click()  
    time.sleep(2)
    pwd = self.driver.find_element(By.ID, "icveObra")
    pwd.send_keys("11-OAX-A")  
    time.sleep(2)        
    self.driver.find_element(By.ID, "buscarObras").click()       
    time.sleep(5)    
    self.driver.find_element(By.CSS_SELECTOR, ".cancelObra").click()   
    time.sleep(5)    
    motivo = self.driver.find_element(By.ID, "motivoCancelacion")
    motivo.send_keys("Prueba motivo de cancelacion robotframework")  
    time.sleep(3)
    self.driver.find_element(By.ID, "file-motivo").send_keys("/home/diego/Downloads/oomd09_6.pdf")
    time.sleep(3)
    self.driver.find_element(By.XPATH, '//*[text()="Cerrar"]').click()       
    time.sleep(3)
    self.driver.find_element(By.XPATH, '//*[text()="Regresar"]').click()           
    time.sleep(3)
    select_edo = Select(self.driver.find_element_by_id("estado"))
    select_edo.select_by_index(20)
    time.sleep(3)
    self.driver.find_element(By.ID, "buscarObras").click()      
    time.sleep(3)
    self.driver.find_element(By.CSS_SELECTOR, ".editObra").click()
    time.sleep(5)



    


    